Extract video src from children
the-grid/html-flatten pull request #85
Opened 2017-01-20 20:32 UTC by GabiThume

Extract src from children of video source tags.

2017-01-20 20:47 UTC, GabiThume commented
@bergie it looks like one possibility for extracting
```
<video>
  <source type="video/mp4" src="foo.mp4"/>
  <source type="video/webm" src="foo.webm"/>
</video>
```
is to use the video key as an Array type, returning
```
video = [
  'foo.mp4',
  'foo.webm'
]
```
or to use it with types as keys
```
video =
  "video/mp4": 'foo.mp4'
  "video/webm": 'foo.webm'
```
what do you think?

2017-01-20 21:21 UTC, bergie commented
@GabiThume currently the schema only allows one video, so first step would be to pick the "best one" (mp4?). We could tweak schema down the line

2017-01-24 12:33 UTC, bergie requested changes
At least remove the logger

2017-01-24 12:33 UTC, bergie commented on index.coffee
> +              console.log child.attribs
Please remove the log

2017-01-24 12:33 UTC, bergie commented on index.coffee
> +        else
Instead of an `else`, this might be better as `if video.attribs.src`

2017-01-24 17:50 UTC, GabiThume commented
@bergie can you please review this again?

2017-01-24 17:51 UTC, bergie approved these changes

2017-01-24 17:51 UTC, merged